/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.gui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import br.senai.sp.jandira.model.Especialidade;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282203
 */
public class EspecialidadeDialog extends javax.swing.JDialog {

    /**
     * Creates new form EspecialidadeDialog
     */
    public EspecialidadeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioPanel = new javax.swing.JPanel();
        paginaPanel = new javax.swing.JPanel();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        nomeEspecialidadeLabel = new javax.swing.JLabel();
        nomeEspecialidadeTextField = new javax.swing.JTextField();
        descricaoEspecialidadeLabel = new javax.swing.JLabel();
        descricaoEspecialidadeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tituloPanel.setBackground(new java.awt.Color(0, 204, 204));
        tituloPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/image/mais.png"))); // NOI18N
        jLabel1.setText("Especialidades - ADICIONAR");
        tituloPanel.add(jLabel1);
        jLabel1.setBounds(70, 0, 460, 90);

        getContentPane().add(tituloPanel);
        tituloPanel.setBounds(0, 0, 800, 90);

        inicioPanel.setBackground(new java.awt.Color(204, 255, 255));
        inicioPanel.setLayout(null);

        paginaPanel.setBackground(new java.awt.Color(204, 255, 255));
        paginaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da Especialidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14), new java.awt.Color(255, 51, 102))); // NOI18N
        paginaPanel.setLayout(null);

        codigoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codigoLabel.setText("Código:");
        paginaPanel.add(codigoLabel);
        codigoLabel.setBounds(40, 60, 90, 20);

        codigoTextField.setEditable(false);
        codigoTextField.setBackground(new java.awt.Color(255, 255, 204));
        codigoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextFieldActionPerformed(evt);
            }
        });
        paginaPanel.add(codigoTextField);
        codigoTextField.setBounds(40, 80, 100, 40);

        buttonCancelar.setBackground(new java.awt.Color(204, 255, 204));
        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/image/delete32.png"))); // NOI18N
        buttonCancelar.setToolTipText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        paginaPanel.add(buttonCancelar);
        buttonCancelar.setBounds(560, 320, 70, 60);

        buttonSalvar.setBackground(new java.awt.Color(204, 255, 204));
        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/image/save32.png"))); // NOI18N
        buttonSalvar.setToolTipText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        paginaPanel.add(buttonSalvar);
        buttonSalvar.setBounds(650, 320, 70, 60);

        nomeEspecialidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeEspecialidadeLabel.setText("Nome da Especialidade:");
        paginaPanel.add(nomeEspecialidadeLabel);
        nomeEspecialidadeLabel.setBounds(40, 150, 170, 20);

        nomeEspecialidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEspecialidadeTextFieldActionPerformed(evt);
            }
        });
        paginaPanel.add(nomeEspecialidadeTextField);
        nomeEspecialidadeTextField.setBounds(40, 170, 580, 40);

        descricaoEspecialidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descricaoEspecialidadeLabel.setText("Descrição da Especialidade:");
        paginaPanel.add(descricaoEspecialidadeLabel);
        descricaoEspecialidadeLabel.setBounds(40, 240, 240, 20);

        descricaoEspecialidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoEspecialidadeTextFieldActionPerformed(evt);
            }
        });
        paginaPanel.add(descricaoEspecialidadeTextField);
        descricaoEspecialidadeTextField.setBounds(40, 260, 680, 40);

        inicioPanel.add(paginaPanel);
        paginaPanel.setBounds(20, 10, 760, 400);

        getContentPane().add(inicioPanel);
        inicioPanel.setBounds(0, 90, 800, 450);

        setSize(new java.awt.Dimension(818, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextFieldActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        Especialidade especialidade = new Especialidade();
        especialidade.setNome(nomeEspecialidadeTextField.getText());
        especialidade.setDescricao(descricaoEspecialidadeTextField.getText());

        EspecialidadeDAO.gravar(especialidade);

        JOptionPane.showMessageDialog(this,
                "Especialidade gravada com sucesso!!",
                "Especialidade",
                JOptionPane.INFORMATION_MESSAGE);

        dispose();

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void nomeEspecialidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEspecialidadeTextFieldActionPerformed


    }//GEN-LAST:event_nomeEspecialidadeTextFieldActionPerformed

    private void descricaoEspecialidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoEspecialidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoEspecialidadeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecialidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel descricaoEspecialidadeLabel;
    private javax.swing.JTextField descricaoEspecialidadeTextField;
    private javax.swing.JPanel inicioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeEspecialidadeLabel;
    private javax.swing.JTextField nomeEspecialidadeTextField;
    private javax.swing.JPanel paginaPanel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
